repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-merge-conflict
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
      - id: pyupgrade
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [ --config=pyproject.toml ]
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)
        args: [ "--profile", "black", "--settings", "pyproject.toml" ]
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.942
  #   hooks:
  #     - id: mypy
  #       args: [ --config=setup.cfg ]
  #       exclude: ^scripts/
  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: 3.9.1
  #   hooks:
  #     - id: flake8
  #       args: [ --config=setup.cfg ]
