train_data_path: data/simulation/train.csv
test_data_path:

cached_features: data/__features.pkl
cached_test_features: data/__simulation_test_features.pkl

predictions_dir: predictions/debug
runners_dir: runners/5_folds_new
model_zoo: configs/models_zoo.yaml

use_regression_models:
  - default_ridge
  - default_dart
  - default_lgbm
  - wild_lgbm
  # - fast_dart
  - default_lasso
  - default_mlp
  - default_mlp_2

use_classification_models: []
  # - default_logreg

stacking_model: stacking_ridge

TimeFolds:
  n_folds: 5
  minifold_size: 60000
  neutral_ratio: 0.05
  test_ratio: 0.2
  train_test_gap: 2000

random_seed: 42
pseudo_target: [40, 50, 60, 75]
