train_data_path: data/xtx_data.csv
test_data_path:

train_topk_features: topk_artefacts
test_topk_features: test_topk_artefacts
cached_features: data/__extended_features.pkl
cached_test_features: data/__extended_test_features.pkl
from_pool: False

usecols:
  - usecols/usecols_fold_0.txt
  - usecols/usecols_fold_1.txt

predictions_dir: predictions/debug
runners_dir: runners/5_folds_extended
model_zoo: configs/models_zoo.yaml

use_regression_models:
  - default_ridge
  - default_dart
  # - default_lgbm
  # - wild_lgbm
  # - fast_dart
  # - default_lasso
  # - one_epoch_mlp
  # - well_reg_mlp

use_classification_models: []
  # - default_logreg

stacking_model: stacking_ridge

TimeFolds:
    n_folds: 5
    minifold_size: 60000
    neutral_ratio: 0.025
    test_ratio: 0.2
    train_test_gap: 2000
# TimeFolds:
#     n_folds: 5
#     minifold_size: 6000
#     neutral_ratio: 0.05
#     test_ratio: 0.2
#     train_test_gap: 2000

random_seed: 42
# pseudo_target: [40, 50, 60, 75]
# pseudo_target: [40, 60, 75]
pseudo_target: [40, ]
